/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;
import com.luoyetx.minicaffe.*;


public class MiniCaffeTest {
    @Test public void testMiniCaffe() {
        System.out.println("Create NIN");
        Net net = new Net("../build/model/nin.prototxt",
                          "../build/model/nin.caffemodel");
        Blob blob = net.getBlob("data");
        // fill data
        int length = blob.data.length;
        for (int i = 0; i < length; i++) {
            blob.data[i] = (float)(Math.random() * 256 - 128);
        }
        blob.syncToC();
        // forward network
        long start = System.currentTimeMillis();
        net.forward();
        long end = System.currentTimeMillis();
        System.out.println("Forward NIN costs " + (end - start) + " ms");
    }
}
